### ISSUE TITLE
logrus.SeverityFormatter is undefined

### ISSUE THREAD

**Issue by elizanp** [araddon/gou#21]
Anyone else getting this error after the last PR (https://github.com/araddon/gou/pull/20)?

```
# github.com/araddon/gou
github.com/araddon/gou/log.go:99: undefined: logrus.SeverityFormatter
```

**Comment by araddon** [comment]
Getting a small upstream fix in to logrus, will merge in asap.

**Comment by joliva-ob** [comment]
+1

**Comment by pineda89** [comment]
+1

**Comment by Ropes** [comment]
I've merged the `github.com/lytics/logrus` branch which contained the `SeverityFormatter` into `master`. Tests of `go get -u github.com/araddon/gou; go build` are working again. 

Apologies for the breakage folks.. I didn't think to test `go get`
